version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY

      - run: aws --profile example sts get-caller-identity

      - aws-cli/setup:
          profile-name: example
          role-arn: AWS_ROLE_TO_ASSUME

      - run: aws --profile example sts get-caller-identity
workflows:
  aws-cli:
    jobs:
      - aws-cli-example
