version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY

      - run: aws sts get-caller-identity

      - run:
          command: |
            aws configure set role_arn AWS_ROLE_TO_ASSUME
            aws configure set source_profile default

      - run: aws configure list
      - run: aws sts get-caller-identity
workflows:
  aws-cli:
    jobs:
      - aws-cli-example
