version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0.6
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup

      - run: aws sts get-caller-identity

      - run:
          command: |
            aws --profile example configure set role_arn $AWS_ROLE_TO_ASSUME
            aws --profile example configure set source_profile default

      - run: aws --profile example sts get-caller-identity
workflows:
  aws-cli:
    jobs:
      - aws-cli-example
